spring.application.name: git-config-server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bhargav124812/git-configs
          username: Bhargav124812
          password: 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
          default-label: master

server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka